apiVersion: 1

contactPoints:
  - orgId: 1
    name: pagerduty-default
    receivers:
      - uid: pagerduty-default-receiver
        type: pagerduty
        settings:
          integrationKey: ${PAGERDUTY_EVENTS_INTEGRATION_KEY}
          severity: '{{ if eq .CommonLabels.severity "critical" }}critical{{ else }}warning{{ end }}'
          class: clear-street-eod-file
          component: grafana-alerting
          group: helioscta-positions
