select
  mm_dd
  ,month
  ,region
  ,min_year_10_yr_normal
  ,max_year_10_yr_normal
  ,years_count_10_yr_normal
  ,min_year_30_yr_normal
  ,max_year_30_yr_normal
  ,years_count_30_yr_normal
  ,electric_cdd_10_yr_normal
  ,electric_hdd_10_yr_normal
  ,gas_cdd_10_yr_normal
  ,gas_hdd_10_yr_normal
  ,population_cdd_10_yr_normal
  ,population_hdd_10_yr_normal
  ,tdd_10_yr_normal
  ,electric_cdd_10_yr_min
  ,electric_hdd_10_yr_min
  ,gas_cdd_10_yr_min
  ,gas_hdd_10_yr_min
  ,population_cdd_10_yr_min
  ,population_hdd_10_yr_min
  ,tdd_10_yr_min
  ,electric_cdd_10_yr_max
  ,electric_hdd_10_yr_max
  ,gas_cdd_10_yr_max
  ,gas_hdd_10_yr_max
  ,population_cdd_10_yr_max
  ,population_hdd_10_yr_max
  ,tdd_10_yr_max
  ,electric_cdd_10_yr_stddev
  ,electric_hdd_10_yr_stddev
  ,gas_cdd_10_yr_stddev
  ,gas_hdd_10_yr_stddev
  ,population_cdd_10_yr_stddev
  ,population_hdd_10_yr_stddev
  ,tdd_10_yr_stddev
  ,electric_cdd_30_yr_normal
  ,electric_hdd_30_yr_normal
  ,gas_cdd_30_yr_normal
  ,gas_hdd_30_yr_normal
  ,population_cdd_30_yr_normal
  ,population_hdd_30_yr_normal
  ,tdd_30_yr_normal
  ,electric_cdd_30_yr_min
  ,electric_hdd_30_yr_min
  ,gas_cdd_30_yr_min
  ,gas_hdd_30_yr_min
  ,population_cdd_30_yr_min
  ,population_hdd_30_yr_min
  ,tdd_30_yr_min
  ,electric_cdd_30_yr_max
  ,electric_hdd_30_yr_max
  ,gas_cdd_30_yr_max
  ,gas_hdd_30_yr_max
  ,population_cdd_30_yr_max
  ,population_hdd_30_yr_max
  ,tdd_30_yr_max
  ,electric_cdd_30_yr_stddev
  ,electric_hdd_30_yr_stddev
  ,gas_cdd_30_yr_stddev
  ,gas_hdd_30_yr_stddev
  ,population_cdd_30_yr_stddev
  ,population_hdd_30_yr_stddev
  ,tdd_30_yr_stddev
from wsi_cleaned.wdd_normals
