select
  date
  ,report_date
  ,revision
  ,max_revision
  ,lower_48
  ,gulf_of_mexico
  ,gulf_coast
  ,north_louisiana
  ,south_louisiana
  ,other_gulf_coast
  ,texas
  ,mid_con
  ,oklahoma
  ,kansas
  ,arkansas
  ,permian
  ,permian_nm
  ,permian_tx
  ,permian_flare_counts
  ,permian_flare_volume
  ,san_juan
  ,rockies
  ,piceance_basin
  ,denver_julesberg
  ,north_dakota_and_montana
  ,uinta_basin
  ,green_wind_river_wyoming
  ,powder_river_basin
  ,other_rockies
  ,west
  ,east
  ,ohio
  ,sw_pennsylvania
  ,ne_pennsylvania
  ,west_virginia
  ,other_east
  ,western_canada
from genscape_cleaned.genscape_daily_pipeline_production
