dbt_azure_postgresql:
  target: azure_postgres
  outputs:
    azure_postgres:
      type: postgres
      host: "{{ env_var('AZURE_POSTGRESQL_DB_HOST', 'heliosctadb.postgres.database.azure.com') }}"
      user: "{{ env_var('AZURE_POSTGRESQL_DB_USER', 'helioscta') }}"
      password: "{{ env_var('AZURE_POSTGRESQL_DB_PASSWORD') }}"
      port: "{{ env_var('AZURE_POSTGRESQL_DB_PORT', '5432') | int }}"
      dbname: helioscta
      schema: dbt
      threads: 12